name: minimal_walking
channels:
  - defaults
  - conda-forge
dependencies:
  - appdirs=1.4.4
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - docker-pycreds=0.4.0
  - eval_type_backport=0.2.2
  - libabseil=20240116.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - pysocks=1.7.1
  - python=3.11.0
  - python_abi=3.11
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - sentry-sdk=2.18.0
  - setproctitle=1.2.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - typing=3.10.0.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wandb=0.19.7
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - async-lru==2.0.4
      - attrs==25.1.0
      - black==25.1.0
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - coacd==1.0.5
      - colorama==0.4.6
      - colorlogging==0.0.2
      - contourpy==1.3.1
      - cryptography==44.0.1
      - cycler==0.12.1
      - cython==3.0.12
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - deprecated==1.2.18
      - dill==0.3.9
      - dnspython==2.7.0
      - email-validator==2.2.0
      - etils==1.12.0
      - filelock==3.17.0
      - fonttools==4.56.0
      - freetype-py==2.5.1
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - genesis-world==0.2.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.8.0
      - grpcio==1.70.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - jinja2==3.1.5
      - kiwisolver==1.4.8
      - kscale==0.3.8
      - lazy-loader==0.4
      - libigl==2.5.1
      - llvmlite==0.44.0
      - lxml==5.3.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - moviepy==2.1.2
      - mpmath==1.3.0
      - mujoco==3.2.5
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - onnx==1.17.0
      - opencv-python==4.11.0.86
      - openexr==3.3.2
      - packaging==24.2
      - pathspec==0.12.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pooch==1.8.2
      - proglog==0.1.10
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - pycollada==0.9
      - pycparser==2.22
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygame==2.6.1
      - pygel3d==0.6.1
      - pyglet==2.1.3
      - pygltflib==1.16.0
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pymeshlab==2023.12.post2
      - pyobjc-core==11.0
      - pyobjc-framework-cocoa==11.0
      - pyopengl==3.1.9
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pyvista==0.44.2
      - rich==13.9.4
      - rsl-rl-lib==2.2.3
      - scikit-image==0.25.2
      - scipy==1.15.2
      - scooby==0.10.0
      - screeninfo==0.8.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - taichi==1.7.3
      - tenacity==9.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tetgen==0.6.4
      - tifffile==2025.2.18
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - typing-inspect==0.9.0
      - vtk==9.3.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yarl==1.18.3
      - zipp==3.21.0
